name = "confident-kids-api"
main = "src/index.js"
compatibility_date = "2023-01-01"

[vars]
JWT_SECRET = "Ay8GGtJ2RKRerBo5o8YvC2mbs5zm0zMbcntl7GbxbAc="
STRIPE_SECRET_KEY = "sk_test_51R55ZbPEQoD1awJQDbDTRm5vQ8ng5R8FB7RVpfrh7ZOElp3PgmiAa17ZmiPOoxksDgaKxOt13DQAJxZEmRJp0wj6003MGORtGG"
STRIPE_MONTHLY_PRICE_ID = "price_your_monthly_price_id"
STRIPE_YEARLY_PRICE_ID = "price_your_yearly_price_id"

[[d1_databases]]
binding = "DB"
database_name = "confident-kids-db"
database_id = "eaa04abe-fb61-4852-8ce0-0ef55cce357a"

[build]
command = "npm install"

[build.upload]
format = "modules"
main = "./src/index.js"

[build.upload.rules]
type = "ESModule"
globs = ["**/*.js"]

