-- Sample seed data for activities table

-- Pillar 1: Independence & Problem-Solving Activities
INSERT INTO activities (id, title, description, pillar_id, min_age, max_age, duration_minutes, instructions, materials, difficulty) VALUES
('act_001', 'The Choice Game', 'Offer your toddler two acceptable choices throughout the day to build decision-making skills.', 1, 2, 5, 15, 'Throughout the day, offer your child two acceptable choices: "Would you like to wear the red shirt or the blue shirt?" "Would you like apple slices or orange slices for snack?" Make sure both options are truly acceptable to you. Praise their decision-making, regardless of which option they choose.', 'Everyday items that offer choice opportunities (clothes, snacks, toys, etc.)', 'easy'),

('act_002', 'Problem-Solving Challenge', 'Present your child with a simple household problem and ask them to come up with three possible solutions.', 1, 6, 11, 20, 'Present a simple household problem like "The remote is missing" or "We need to organize these toys." Ask your child to think of three possible solutions before choosing one to try. Guide them with questions if needed, but avoid giving them the answers.', 'Paper and pencil for writing down solutions (optional)', 'medium'),

('act_003', 'Independent Project', 'Challenge your teen to plan and execute a small project from start to finish without your help.', 1, 12, 18, 60, 'Challenge your teen to plan and execute a small project from start to finish without your help. This could be cooking a meal, planning a family activity, or organizing a space in your home. Ask them to create a plan first, then execute it. Discuss the process afterward, focusing on what they learned and how they handled challenges.', 'Project-specific materials', 'hard');

-- Pillar 2: Growth Mindset & Resilience Activities
INSERT INTO activities (id, title, description, pillar_id, min_age, max_age, duration_minutes, instructions, materials, difficulty) VALUES
('act_004', 'The "Yet" Game', 'Help your toddler reframe challenges by adding "yet" to statements about things they cannot do.', 2, 2, 5, 10, 'When your child says "I can''t do it," gently add the word "yet" to their statement: "You can''t do it yet, but you''re learning!" Make it into a game by taking turns saying things you can''t do "yet" but are working on.', 'None', 'easy'),

('act_005', 'Growth Mindset Journal', 'Create a journal to track challenges, efforts, and progress over time.', 2, 6, 11, 15, 'Help your child create a journal where they can record challenges they face, efforts they make, and progress they see. Each entry should include: 1) What was challenging, 2) What they did to work on it, 3) What they learned or how they improved. Review entries periodically to celebrate growth.', 'Notebook or journal, colored pencils or markers', 'medium'),

('act_006', 'Failure Resume', 'Create a "resume" of failures and what was learned from each experience.', 2, 12, 18, 30, 'Guide your teen in creating a "failure resume" that lists setbacks, challenges, or failures they''ve experienced and what they learned from each. Discuss how these experiences contributed to their growth and development. Share examples from your own life to normalize failure as part of the learning process.', 'Paper and pen, or digital document', 'medium');

-- Pillar 3: Social Confidence & Communication Activities
INSERT INTO activities (id, title, description, pillar_id, min_age, max_age, duration_minutes, instructions, materials, difficulty) VALUES
('act_007', 'Puppet Conversations', 'Use puppets or stuffed animals to practice simple conversations and social interactions.', 3, 2, 5, 15, 'Use puppets or stuffed animals to act out simple conversations and social interactions. Model greetings, asking questions, and taking turns. Let your child practice with the puppets, then gradually encourage them to use these skills in real interactions.', 'Puppets or stuffed animals', 'easy'),

('act_008', 'Conversation Starters Jar', 'Create a jar of conversation starters for your child to practice initiating and maintaining conversations.', 3, 6, 11, 20, 'Together with your child, write down interesting conversation starters on small slips of paper and put them in a jar. Examples: "What would you do if you could fly?" or "What''s your favorite memory?" Practice using these starters during family meals or car rides. Encourage follow-up questions and active listening.', 'Jar, paper slips, pens or markers', 'medium'),

('act_009', 'Social Scenario Workshop', 'Role-play challenging social scenarios to build confidence in handling difficult situations.', 3, 12, 18, 30, 'Identify social scenarios your teen finds challenging (e.g., joining a group conversation, disagreeing respectfully, or asking for help). Role-play these scenarios together, brainstorming different approaches and practicing responses. Discuss what worked well and what could be improved.', 'List of scenarios (can be written on cards)', 'hard');

-- Pillar 4: Purpose & Strength Discovery Activities
INSERT INTO activities (id, title, description, pillar_id, min_age, max_age, duration_minutes, instructions, materials, difficulty) VALUES
('act_010', 'I''m Good At...', 'Help your toddler identify and celebrate things they can do well.', 4, 2, 5, 10, 'Throughout the day, notice and name things your child does well: "You''re good at stacking blocks!" or "You''re really good at finding your shoes!" Create a simple chart with pictures of things they can do well and review it together regularly.', 'Paper, markers, stickers', 'easy'),

('act_011', 'Strength Spotting', 'Help your child identify their character strengths through daily activities and stories.', 4, 6, 11, 20, 'Introduce the concept of character strengths (kindness, creativity, perseverance, etc.) through stories and examples. Throughout the week, "spot" these strengths when your child displays them: "I noticed how persistent you were with that puzzle!" Create a strength journal where they can record examples of using their top strengths.', 'Notebook, list of character strengths with child-friendly definitions', 'medium'),

('act_012', 'Purpose Project', 'Guide your teen in exploring how their strengths can be used to contribute to something meaningful.', 4, 12, 18, 45, 'Help your teen identify their top strengths and interests. Discuss how these could be used to contribute to something meaningful to them. Guide them in designing a small project that connects their strengths to a purpose (e.g., using artistic skills to create cards for a nursing home, or tech skills to help a local nonprofit).', 'Strength assessment tools, project planning worksheet', 'hard');

-- Pillar 5: Managing Fear & Anxiety Activities
INSERT INTO activities (id, title, description, pillar_id, min_age, max_age, duration_minutes, instructions, materials, difficulty) VALUES
('act_013', 'Calm-Down Corner', 'Create a special space where your toddler can go to calm down when feeling big emotions.', 5, 2, 5, 15, 'Create a cozy corner with soft pillows, stuffed animals, and calming items like sensory bottles or soft books. Introduce this as a special place to go when feeling big emotions. Practice using calming strategies together: deep breaths, hugging a stuffed animal, or looking at a calming jar.', 'Pillows, stuffed animals, sensory bottles, books about emotions', 'easy'),

('act_014', 'Worry Monster', 'Create a "worry monster" that eats written or drawn worries to help children externalize and manage anxieties.', 5, 6, 11, 25, 'Create a "worry monster" from a box with a slot cut in the top and decorated with a friendly monster face. Encourage your child to write or draw their worries on paper and feed them to the monster. Discuss each worry first, helping them reframe it or develop a plan to address it.', 'Box, art supplies, paper, pencils', 'medium'),

('act_015', 'Fear Reframing Workshop', 'Teach teens to identify and reframe anxious thoughts using cognitive-behavioral techniques.', 5, 12, 18, 30, 'Introduce the concept that thoughts influence feelings and behaviors. Teach your teen to identify anxious thoughts and evaluate their accuracy. Practice reframing negative thoughts into more balanced perspectives. Create a personal "thought reframing" guide they can reference when feeling anxious.', 'Thought record worksheets, pen', 'hard');
